# Generated by Django 3.0.7 on 2020-06-09 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runtime', models.FloatField()),
                ('result_length', models.IntegerField()),
                ('result_image', models.ImageField(upload_to='results_images')),
                ('result_date', models.DateField(verbose_name='date tested')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sa.Table')),
            ],
        ),
    ]
