# Generated by Django 3.0.7 on 2020-06-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa', '0002_auto_20200612_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='reduction_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='result',
            name='start_temp',
            field=models.FloatField(default=0.0),
        ),
    ]
