# Generated by Django 3.0.7 on 2020-06-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa', '0004_result_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='count_increase',
            field=models.IntegerField(default=1.2),
        ),
        migrations.AddField(
            model_name='result',
            name='sa_num',
            field=models.IntegerField(default=0),
        ),
    ]
